#!/usr/bin/env node

/**
 * This is a simple visualizer script created to help you
 * understand the network traces generated by the 'parse_trace.js' script.
 */

const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

function visualize_trace(csv_file, output_file = null) {
    try {
        const data = fs.readFileSync(csv_file, 'utf8');
        const lines = data.trim().split('\n');

        if (lines.length < 2) {
            throw new Error('Incorrect csv format');
        }

        const data_points = [];
        for (let i = 1; i < lines.length; i++) {
            const line = lines[i].trim();
            if (!line) continue;

            const [time, rate] = line.split(',');
            if (time && rate) {
                data_points.push({
                    x: parseFloat(time),
                    y: parseFloat(rate)
                });
            }
        }

        if (data_points.length === 0) {
            throw new Error('No valid data points in file');
        }

        if (!output_file) {
            const base_name = path.parse(csv_file).name;
            output_file = `${base_name}_chart.html`;
        }

        const html = generate_html(data_points, csv_file);

        fs.writeFileSync(output_file, html);

        return output_file;

    } catch (error) {
        console.error(`error: ${error.message}`);
        return null;
    }
}

function generate_html(data_points, source_file) {
    const max_rate = Math.max(...data_points.map(p => p.y));
    const max_time = Math.max(...data_points.map(p => p.x));

    // The below HTML document is generated using AI
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Network Trace Chart</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background: #1a1a1a;
            color: #e5e5e5;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0 0 5px 0;
            font-size: 24px;
            font-weight: 600;
            color: #ffffff;
        }

        .source {
            font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
            font-size: 14px;
            color: #b0b0b0;
            background: #2d2d2d;
            padding: 4px 8px;
            border-radius: 4px;
            display: inline-block;
        }

        .stats {
            display: flex;
            justify-content: center;
            gap: 40px;
            margin-bottom: 30px;
            padding: 15px;
            background: #2d2d2d;
            border-radius: 6px;
            border: 1px solid #404040;
        }

        .stat {
            text-align: center;
        }

        .stat_value {
            font-size: 20px;
            font-weight: 600;
            color: #ffffff;
            margin-bottom: 2px;
        }

        .stat_label {
            font-size: 12px;
            color: #b0b0b0;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .chart_container {
            background: #2d2d2d;
            border: 1px solid #404040;
            border-radius: 6px;
            padding: 20px;
            height: 500px;
            position: relative;
        }

        @media (max-width: 768px) {
            .stats {
                flex-direction: column;
                gap: 15px;
            }
            
            .stats {
                display: grid;
                grid-template-columns: 1fr 1fr;
                gap: 20px;
            }
            
            body {
                padding: 15px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="source">${path.basename(source_file)}</div>
        </div>

        <div class="stats">
            <div class="stat">
                <div class="stat_value">${data_points.length.toLocaleString()}</div>
                <div class="stat_label">Points</div>
            </div>
            <div class="stat">
                <div class="stat_value">${max_time.toFixed(0)}s</div>
                <div class="stat_label">Duration</div>
            </div>
            <div class="stat">
                <div class="stat_value">${max_rate.toFixed(0)}</div>
                <div class="stat_label">Peak (kbps)</div>
            </div>
        </div>

        <div class="chart_container">
            <canvas id="trace_chart"></canvas>
        </div>
    </div>

    <script>
        const ctx = document.getElementById('trace_chart').getContext('2d');
        
        const chart = new Chart(ctx, {
            type: 'line',
            data: {
                datasets: [{
                    label: 'Link Rate (kbps)',
                    data: ${JSON.stringify(data_points)},
                    borderColor: '#60a5fa',
                    backgroundColor: 'rgba(96, 165, 250, 0.1)',
                    borderWidth: 2,
                    fill: true,
                    tension: 0.1,
                    pointRadius: 0,
                    pointHoverRadius: 5,
                    pointHoverBackgroundColor: '#60a5fa',
                    pointHoverBorderColor: '#2d2d2d',
                    pointHoverBorderWidth: 2
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                interaction: {
                    intersect: false,
                    mode: 'index'
                },
                plugins: {
                    legend: {
                        display: false
                    },
                    tooltip: {
                        backgroundColor: 'rgba(45, 45, 45, 0.95)',
                        titleColor: '#ffffff',
                        bodyColor: '#e5e5e5',
                        borderColor: '#404040',
                        borderWidth: 1,
                        cornerRadius: 4,
                        displayColors: false,
                        titleFont: {
                            size: 13
                        },
                        bodyFont: {
                            size: 12
                        },
                        padding: 8,
                        callbacks: {
                            title: function(context) {
                                return context[0].parsed.x + 's';
                            },
                            label: function(context) {
                                return context.parsed.y.toFixed(1) + ' kbps';
                            }
                        }
                    }
                },
                scales: {
                    x: {
                        type: 'linear',
                        display: true,
                        title: {
                            display: true,
                            text: 'Time (seconds)',
                            color: '#b0b0b0',
                            font: {
                                size: 12
                            }
                        },
                        grid: {
                            color: '#404040',
                            drawBorder: false
                        },
                        ticks: {
                            color: '#b0b0b0',
                            font: {
                                size: 11
                            }
                        }
                    },
                    y: {
                        display: true,
                        title: {
                            display: true,
                            text: 'Link Rate (kbps)',
                            color: '#b0b0b0',
                            font: {
                                size: 12
                            }
                        },
                        beginAtZero: true,
                        grid: {
                            color: '#404040',
                            drawBorder: false
                        },
                        ticks: {
                            color: '#b0b0b0',
                            font: {
                                size: 11
                            }
                        }
                    }
                }
            }
        });
    </script>
</body>
</html>`;
}

function open_in_browser(html_file) {
    const full_path = path.resolve(html_file);
    const command = process.platform === 'darwin' ? 'open' :
        process.platform === 'win32' ? 'start' : 'xdg-open';

    exec(`${command} "${full_path}"`, (error) => {
        if (error) {
            console.log(`couldn't auto-open, try opening manually: ${full_path}`);
        }
    });
}

if (require.main === module) {
    const args = process.argv.slice(2);

    if (args.includes('-h') || args.includes('--help') || args.length == 0) {
        console.log(`usage: node trace_visualizer.js <csv_file> [output_file] [--open]`);
        process.exit(0);
    }

    const csv_file = args[0];
    let output_file = null;
    let should_open = false;

    for (let i = 1; i < args.length; i++) {
        if (args[i] === '--open') {
            should_open = true;
        } else if (!args[i].startsWith('--') && !output_file) {
            output_file = args[i];
        }
    }

    const result_file = visualize_trace(csv_file, output_file);

    if (result_file) {
        if (should_open) {
            open_in_browser(result_file);
        }
    }
    process.exit(0);
}